const a = 5;

try {
  a = 3;
} catch (error) {
  console.log(error);
}

console.log(a);
